### ISSUE TITLE
audit_log did not log ManyToManyField

### ISSUE THREAD

**Issue by danieldias51** [vvangelovski/django-audit-log#10]
The audit_log did not log the many to many fields.
Django creates me a table to record the foreign keys.
example:

class registry (models.Model)
    """
    other fields...
    """
    Equips = models.ManyToManyField(Equipment,verbose_name ="Equipments")

django automaticly creates me a table "registry_Equips", to store multi foreignKeys for Equips

Syncdb creates the table "registry" and "table_registryauditlogentry"
But for ManyToManyField fields do not create the table "registry_Equipsauditlogentry"
only creates "registry_Equip" and i can't log changes

**Comment by eriktelepovsky** [comment]
http://django-auditlog.readthedocs.io/en/latest/usage.html#many-to-many-relationships
